export function generateThreatReport(result, explanation) {
  if (!result) return '';
  const { assessment, indicators, threat_intelligence } = result;
  const score = assessment?.risk_score ?? 0;
  const level = assessment?.risk_level ?? 'UNKNOWN';
  const status = assessment?.assessment_status ?? 'unknown';

  const dateStr = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

  const lines = [
    `# 🛡️ ScamGraph Threat Intelligence Report`,
    `Generated: ${dateStr}`,
    ``,
    `## Summary`,
    `- **Risk Level:** ${level}`,
    `- **Risk Score:** ${score} / 100`,
    `- **Assessment Status:** ${status}`,
  ];

  if (assessment?.risk_level_reason) {
    lines.push(`- **Notice:** ${assessment.risk_level_reason}`);
  }
  if (assessment?.scope) {
    lines.push(`- **Scope:** ${assessment.scope}`);
  }
  lines.push(``);

  lines.push(`## Extracted Indicators`);
  lines.push(`- **URLs (${indicators?.urls?.length || 0}):** ${indicators?.urls?.length ? indicators.urls.join(', ') : 'None'}`);
  lines.push(`- **Domains (${indicators?.domains?.length || 0}):** ${indicators?.domains?.length ? indicators.domains.join(', ') : 'None'}`);
  lines.push(`- **Emails (${indicators?.emails?.length || 0}):** ${indicators?.emails?.length ? indicators.emails.join(', ') : 'None'}`);
  lines.push(``);

  if (assessment?.heuristic_findings?.length) {
    lines.push(`## Local Warning Signs`);
    assessment.heuristic_findings.forEach((finding) => {
      lines.push(`- **${finding.description} (+${finding.score})**: "${finding.matched_text}"`);
    });
    lines.push(``);
  }

  const vt = threat_intelligence?.virustotal?.[0];
  const uh = threat_intelligence?.urlhaus?.[0];
  const gsb = threat_intelligence?.google_safe_browsing?.[0];
  const ip = threat_intelligence?.ipinfo?.[0];

  if (vt || uh || gsb || ip) {
    lines.push(`## External Threat Intelligence (First URL)`);
    if (vt) {
      const stats = vt.stats ? `${vt.stats.malicious} malicious, ${vt.stats.suspicious} suspicious` : 'N/A';
      lines.push(`- **VirusTotal:** status=${vt.status}, detections=${stats}`);
    }
    if (uh) {
      lines.push(`- **URLhaus:** status=${uh.status}, malicious=${uh.malicious ? 'Yes' : 'No'}`);
    }
    if (gsb) {
      const types = gsb.threat_types?.length ? gsb.threat_types.join(', ') : 'None';
      lines.push(`- **Google Safe Browsing:** status=${gsb.status}, flagged=${gsb.flagged ? 'Yes' : 'No'} (${types})`);
    }
    if (ip) {
      const details = ip.status === 'ok' ? `${ip.ip} (${ip.country || 'Unknown'}, ${ip.as_name || 'N/A'})` : ip.status;
      lines.push(`- **IPinfo:** ${details}`);
    }
    lines.push(``);
  }

  if (explanation?.explanation) {
    lines.push(`## Plain-English Explanation`);
    lines.push(explanation.explanation);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Report generated by ScamGraph · Hack Atlantic 2026*`);

  return lines.join('\n');
}
